name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Build
      run: go build -v ./...

    - name: Test URL Delete
      run: go test -v ./internal/http-server/handlers/url/delete/delete_test.go
    - name: Test URL Save
      run: go test -v  ./internal/http-server/handlers/url/save/save_test.go
    - name: Test Redirect
      run: go test -v  ./internal/http-server/handlers/redirect/redirect_test.go
    - name: Test Rundom
      run: go test -v ./internal/lib/random/random_test.go